### ISSUE TITLE
Summary of usable data

### ISSUE THREAD

**Issue by tzebre** [ivadomed/model-spinal-rootlets#1]
# Reminder on how to spot rootlets on an MRI: 
Not visible on T1w, but visible in T2w MRI. 
<img width="414" alt="Capture d’écran 2023-05-15 à 08 46 41" src="https://github.com/ivadomed/model-spinal-rootlets/assets/58122097/536c8bc7-b510-47cc-9401-3a49ff4150f2">
_Rootlets pointed by red arrow, dataset: ds004507/sub-002_ses_headNormal T2w isotropic 0.6_

# Available data
## 1. [ds004507](https://openneuro.org/datasets/ds004507/versions/1.0.1) --> [pmj-based-csa](https://github.com/sct-pipeline/pmj-based-csa)
11 subject (3 head position each), BIDS sructure
- suffix `_spinalroots.nii.gz` une voxel on center of the cord at midle spinal rootlet level 
<img width="500" alt="Capture d’écran 2023-05-11 à 11 49 16" src="https://github.com/ivadomed/model-spinal-rootlets/assets/58122097/fbcca657-2484-4bc6-9f69-99e0aa22600f">

**No voxel labeling of rootlet** 

## 2. Benjamin de Leener data 
info: [CSV info](https://docs.google.com/spreadsheets/d/1nMTs6yJzY-w0tAmZYrzOHnGL-8oo9Wq3tnCPM6Shs8o/edit#gid=0)
Data: [Drive](https://drive.google.com/drive/folders/1-B7oTTCx1TNTvFXI-hw-NWUC0_dar5WO)
- .nrrd file
Center1 Cadotte subject: 01_t2-label.nrrd
```
OrderedDict([('type', 'short'),
             ('dimension', 3),
             ('space', 'left-posterior-superior'),
             ('sizes', array([ 64, 320, 320])),
             ('space directions',
              array([[ 8.00000012e-01,  3.63901229e-08,  4.17830259e-09],
                     [ 3.63901236e-08, -7.79180780e-01, -1.81321073e-01],
                     [ 4.17830267e-09, -1.81321073e-01,  7.79180780e-01]])),
             ('kinds', ['domain', 'domain', 'domain']),
             ('endian', 'little'),
             ('encoding', 'gzip'),
             ('space origin',
              array([ -21.58555412,  143.32038879, -188.45478821]))])
```
UNF sct_004 (corresponding to sub_01 according to CSV)
```
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b'?TR:1500.000 TE:11'
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3 320 320  64   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int16
bitpix          : 16
slice_start     : 0
pixdim          : [-1.000000e+00  8.000000e-01  8.000000e-01  8.000000e-01  1.500000e+00
  1.000000e+00  1.000000e+00  5.511571e+04]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 255
glmin           : 0
descrip         : b''
aux_file        : b''
qform_code      : scanner
sform_code      : scanner
quatern_b       : 0.446931
quatern_c       : -0.5628768
quatern_d       : -0.43235058
qoffset_x       : -13.209519
qoffset_y       : 89.81659
qoffset_z       : -273.07306
srow_x          : [-6.0117296e-03 -2.5833905e-02  7.9956019e-01 -1.3209519e+01]
srow_y          : [-0.77918077  0.18132104  0.         89.81659   ]
srow_z          : [ 1.8122135e-01  7.7875239e-01  2.6524169e-02 -2.7307306e+02]
intent_name     : b''
magic           : b'n+1'
``` 
<img width="215" alt="Capture d’écran 2023-05-15 à 09 02 32" src="https://github.com/ivadomed/model-spinal-rootlets/assets/58122097/c2ad1546-6961-42b1-a36c-43a2b65ac526"> <img width="120" alt="Capture d’écran 2023-05-15 à 09 03 03" src="https://github.com/ivadomed/model-spinal-rootlets/assets/58122097/0f3b329c-cd0f-4dd9-b012-0d95fc89ef08">
_sub_unfSCT004_T2w.nii.gz, and Center1 Cadotte sub 01 in 3D Slicer_
**In 3D slicer the label does not correspond**

## 3. TWH data 
.nrrd 0.39 isotropic
<img width="217" alt="Capture d’écran 2023-05-15 à 09 08 53" src="https://github.com/ivadomed/model-spinal-rootlets/assets/58122097/d9a35890-181c-4cb3-9ab6-0a91e6ef776a"><img width="94" alt="Capture d’écran 2023-05-15 à 09 09 05" src="https://github.com/ivadomed/model-spinal-rootlets/assets/58122097/0261189c-c35a-4d70-b4ab-1be983331196"><img width="99" alt="Capture d’écran 2023-05-15 à 09 08 59" src="https://github.com/ivadomed/model-spinal-rootlets/assets/58122097/04c9118b-d69a-49c7-88d5-e9dc46c8fef5">

_13696-label.nrrd, 13696.nrrd in 3D Slicer _
**No label directly on the voxel**

**Comment by tzebre** [comment]
# Pipeline considered for project:
## 1) Segment the CSF 
- Rootlets are only localizable in this ROI
- Can the surrounding areas provide clues to the presence of rootlets?

**Comment by jcohenadad** [comment]
> Use the work of [Rohan](https://github.com/ivadomed/model_seg_csf_epi/tree/rb/preprocess_register-multimodal) and the model trained for CSF segmentation.

How will that be useful? Also, I would create a separate issue (this issue is specific to "Summary of usable data", so not about the processing pipeline)

**Comment by jcohenadad** [comment]
Given the variety of existing labels, how about you try to segment the actual rootlets (ie: not only the center of rootlets as a single point, but the _actual_ rootlets)

**Comment by tzebre** [comment]
> > Use the work of [Rohan](https://github.com/ivadomed/model_seg_csf_epi/tree/rb/preprocess_register-multimodal) and the model trained for CSF segmentation.
> 
> How will that be useful? Also, I would create a separate issue (this issue is specific to "Summary of usable data", so not about the processing pipeline)

Yes, I totally agree, I'll create a new topic. 
My goal was to use the CSF segmentation and after a thresholding as a first automatic step to label the data (this technique seem to have decent results during testing). Of course I would double check, but it will speed up the labeling process.

**Comment by tzebre** [comment]
> Given the variety of existing labels, how about you try to segment the actual rootlets (ie: not only the center of rootlets as a single point, but the _actual_ rootlets). You could start by manually segmenting some of them on 10-20 subjects, and see how a simple nnUnet learns

Yes, I think I'll do that. Even if the model is not perfect with the first set of data, it will help to label new subjects just by correcting the errors.  

To follow up on the second possible lead I mentioned at the last meeting:
My idea of using multiple instance learning with slice-level labeling rather than voxel-level labeling seems tricky, especially considering that MRIs have poor resolution compared to histological data, which is the main application I've found in the literature [Attention-based Deep Multiple Instance Learning](https://arxiv.org/pdf/1802.04712.pdf.)
