### ISSUE TITLE
Cadotte et al 2015 prediction problems 

### ISSUE THREAD

**Issue by tzebre** [ivadomed/model-spinal-rootlets#11]
I have tried to predict the nerve segmentation of the article images but the results are really bad. C2-C3 are labeled some T1-T2 also but a lot of images have no segmentation on the middle levels. 

<img width="1353" alt="Capture d’écran 2023-08-03 à 10 45 53" src="https://github.com/ivadomed/model-spinal-rootlets/assets/58122097/26842e8a-4841-48ca-9bbb-bf9df795c9bc">

A possible explanation, the resolution is .3mm model has only been trained on 0.6 and 0.8. On a 0.3mm image you can see individual rootlets:
<img width="355" alt="Capture d’écran 2023-08-03 à 11 58 10" src="https://github.com/ivadomed/model-spinal-rootlets/assets/58122097/fe978fc5-70ef-4642-bf8e-d7e2f22def1d">

I have tried to oversample the image to .7mm before the prediction. The same problem appears middle spinal levels are not labeled, but it looks like C2-C3 levels have a better labeling.

**Comment by jcohenadad** [comment]
> I have tried to oversample the image to .7mm before the prediction.

You meant downsample (oversample is going from low res to high res)

**Comment by valosekj** [comment]
Predictions seem to be better with [M5 `fold_all` model](https://github.com/ivadomed/model-spinal-rootlets/pull/23#issuecomment-1888047165):

<img width="1000" alt="image" src="https://github.com/ivadomed/model-spinal-rootlets/assets/39456460/ba2a2259-44b4-484b-a0a1-1df90fa8c229">

--> closing
