### ISSUE TITLE
Possible strategy: segment the CSF and use thresholding to identify the nerve roots

### ISSUE THREAD

**Issue by tzebre** [ivadomed/model-spinal-rootlets#2]
## Description

In order to facilitate the manual segmentation of nerve roots, the idea is to segment the CSF to obtain an ROI, and then threshold the signal inside the ROI to only keep pixels below a certain threshold. 

## Additional context

> Use the work of [Rohan](https://github.com/ivadomed/model_seg_csf_epi/tree/rb/preprocess_register-multimodal) and the model trained for CSF segmentation.

> How will that be useful? Also, I would create a separate issue (this issue is specific to "Summary of usable data", so not about the processing pipeline)

_Originally posted by @jcohenadad in https://github.com/ivadomed/model-spinal-rootlets/issues/1#issuecomment-1550541781_

Yes, I totally agree, I'll create a new topic. 
My goal was to use the CSF segmentation and after a thresholding as a first automatic step to label the data (this technique give decent results during testing). Of course I would double check, but it will speed up the labeling process.

**Comment by tzebre** [comment]
## Test result with thresholding 
CSF was obtained using the model trained with data_example_spinegeneric 
Model Details : 
!TODO!

Thresholding with the basics filter from [skimage.filter](https://scikit-image.org/docs/stable/auto_examples/segmentation/plot_thresholding.html)

![output](https://github.com/ivadomed/model-spinal-rootlets/assets/58122097/0a54580e-cfb7-4961-8187-eeb8bf30ec07)
_CSF area of ds004507/sub-002_ses-headNormal_T2w_

![outputmulti](https://github.com/ivadomed/model-spinal-rootlets/assets/58122097/43e01b0d-77c6-46f8-b518-ac3f69fe8a15)

**The rootlets are well kept by some threshold filter, but the inner and outer borders of the CSF are also kept (need to investigate if it's because of a bad CSF segmentation or not)**.

**Comment by jcohenadad** [comment]
You might want to look at ITKsnap for their semi-automatic labeling tool

**Comment by tzebre** [comment]
Strategy abandoned because results are good with nnUNetV2 without CSF segmentation.
