### ISSUE TITLE
Benjamin De Leener dataset: Images don't seem to correspond to the associated label

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/model-spinal-rootlets#3]
Information about the data and associated labels: [CSV info](https://docs.google.com/spreadsheets/d/1nMTs6yJzY-w0tAmZYrzOHnGL-8oo9Wq3tnCPM6Shs8o/edit#gid=0)
Link to labels: [Drive](https://drive.google.com/drive/folders/1-B7oTTCx1TNTvFXI-hw-NWUC0_dar5WO)

It looks like the images that are listed in the [google sheet](https://docs.google.com/spreadsheets/d/1nMTs6yJzY-w0tAmZYrzOHnGL-8oo9Wq3tnCPM6Shs8o/edit#gid=0) do not seem to correspond to the associated label.

Example:
`sub-unfSCT004_T2w.nii.gz` (from git-annex version ec751937485e0027712cae24385a0d60696e8df2) is supposedly associated with `01_t2-label.nrrd`, according to:

<img width="1047" alt="image" src="https://github.com/ivadomed/model-spinal-rootlets/assets/2482071/16a9f6c0-01b8-4011-84c2-aab77d351077">

The .nrrd header has the following qform (it was opened in 3D Slicer, and then converted to a NIfTI file, and then read with fslhd)
```
qto_xyz:1	-0.800000 -0.000000 -0.000000 21.585554 
qto_xyz:2	-0.000000 0.779181 0.181321 -143.320389 
qto_xyz:3	0.000000 -0.181321 0.779181 -188.454788 
```

While the image has a very different qform:
```
qto_xyz:1	-0.006012 -0.025834 0.799560 -13.209519 
qto_xyz:2	-0.779181 0.181321 0.000000 89.816589 
qto_xyz:3	0.181221 0.778752 0.026524 -273.073059 
```

This suggests that the matching of subject-label is incorrect. Maybe @benjamindeleener you have some insights?

Not surprisingly, the label do not correspond to the rootlets when overlaid in 3D Slicer:

<img width="215" alt="Capture d’écran 2023-05-15 à 09 02 32" src="https://github.com/ivadomed/model-spinal-rootlets/assets/58122097/c2ad1546-6961-42b1-a36c-43a2b65ac526"> <img width="120" alt="Capture d’écran 2023-05-15 à 09 03 03" src="https://github.com/ivadomed/model-spinal-rootlets/assets/58122097/0f3b329c-cd0f-4dd9-b012-0d95fc89ef08">

**Comment by tzebre** [comment]
## qform comparaison 
To compare qform of the image and is coresponding label based on the [google sheet](https://docs.google.com/spreadsheets/d/1nMTs6yJzY-w0tAmZYrzOHnGL-8oo9Wq3tnCPM6Shs8o/edit#gid=0) I've created a [notebook](https://github.com/ivadomed/model-spinal-rootlets/blob/main/open_compare.ipynb) that does this:
- Convert .nrrd label to nifti file using [pnlbwh/conversion package](https://github.com/pnlbwh/conversion).
- display the qform of the nifti image and label ([Fslutils](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Fslutils)) but also the space directions of the original .nrrd label ([pynrrd package](https://pypi.org/project/pynrrd/))

I get the same results as julien above 
<img width="530" alt="Capture d’écran 2023-05-18 à 11 09 31" src="https://github.com/ivadomed/model-spinal-rootlets/assets/58122097/37f5d50a-311d-459b-ac63-004f5b07f8e9">


## Missing information on datas 
unfSCT> 017 does not exist in sct_testing_large, so what are the original images? 
Center 2: Paris or Paris2017?
