### ISSUE TITLE
Ventral rootlets - results of first segmentation model

### ISSUE THREAD

**Issue by LouisThomasLapointe** [ivadomed/model-spinal-rootlets#36]
**1) Dataset**
The first training was done on 14 subjects (segmented manually by LTL) from the spine-generic and OpenNeuro datasets. Manual segmentation of the ventral rootlets was done while the dorsal rootlets' segmentation were taken from the D5 dataset described [here](https://github.com/ivadomed/model-spinal-rootlets/tree/main/training). 
**2) Model training**
nnUNet 3d_fullres model trained on 14 subjects.
To initialize the dataset, the following command was used:
`nnUNetv2_plan_and_preprocess -d 101 --verify_dataset_integrity -c  3d_fullres`

For starting the training, the following command was used:
`CUDA_VISIBLE_DEVICES=0 nnUNetv2_train 101 3d_fullres 0`

For running the inference on new images, the following command was used:
`nnUNetv2_predict -i nnUNet_raw/Dataset103_M1/imagesTr -o nnUNet_raw/Dataset103_M1/labelsTr -d 101 -c 3d_fullres -f 0`
Where the Dataset103_M1 folder contains the images on which inference was run.

**3) Results**

<details><summary>Here are the learning curves for the training. </summary>

![progress](https://github.com/ivadomed/model-spinal-rootlets/assets/146556291/a1b21630-d6d5-49b6-848d-56455f3a2e7a)

</details>

Here is an example of the prediction the model give:
The image
![image](https://github.com/ivadomed/model-spinal-rootlets/assets/146556291/ae6d7df7-b243-4a30-9e48-4a79283f3ca6)
The segmentation
![image](https://github.com/ivadomed/model-spinal-rootlets/assets/146556291/2404ce7b-c725-41c4-973f-16036454a885)

We can see that, while not perfect, the predictions the model can produce are promising for a first training on a relatively small dataset. There is some obvious problem with the model, mainly incorrect labelisation of pixels around the rootlets as rootlets pixel, incomplete segmentation of an individual rootlet and incorrect labelisation of rootlets pixels as background pixel. Those errors are all visible in the image below.
![image](https://github.com/ivadomed/model-spinal-rootlets/assets/146556291/b6d90734-591a-4a6f-82ce-968885f9f250)
![image](https://github.com/ivadomed/model-spinal-rootlets/assets/146556291/1f9d9799-8deb-44ae-8074-af13ee34ad1d)

Finally, there is some rootlets, especially in the lower cervical levels, that are associated with the wrong spinal level. The problem is rare, but tends to happen in already challenging to segment MRI images or ones where the levels are really close one to another.
![image](https://github.com/ivadomed/model-spinal-rootlets/assets/146556291/4edcc5b3-1e60-4099-af20-83d8cdf47abc)

**Comment by jcohenadad** [comment]
Very nice results @LouisThomasLapointe ! Keep up the good work 😊

**Comment by valosekj** [comment]
@LouisThomasLapointe nice results! 🚀 

> Finally, there is some rootlets, especially in the lower cervical levels, that are associated with the wrong spinal level. The problem is rare, but tends to happen in already challenging to segment MRI images or ones where the levels are really close one to another.

This happened to us during dorsal rootlets training in a few subjects too. We QCed the predicted images and fixed the problematic levels manually.

A two minor comments/suggestions:
1. Could you upload a TSV file listing the subjects you used for the training/testing to [training/dataset_creation](https://github.com/ivadomed/model-spinal-rootlets/tree/main/training/dataset_creation)? You can name the file `V1.tsv` (V = ventral). Please inlcude two columns: `file_name` (e.g., sub-amu01_T2w.nii.gz) and `folder` (train/test). You can do so by cloning the repo, creating a new branch, adding the file, committing the file, pushing the file, and opening a PR. Tutorial [here](https://intranet.neuro.polymtl.ca/geek-tips/git.html#clone-specific-branch).
2. Can you please try to generate QC for the predicted images? It will allow us a convenient assessment of the rootlets across all subjects. To do so: [download and install the latest SCT](https://github.com/spinalcordtoolbox/spinalcordtoolbox?tab=readme-ov-file#installation), run the first `sct_qc` command from [this comment](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4166#issuecomment-1654175610) (you will need SC seg which is used to crop the image; you can get it by running `sct_deepseg_sc`), loop across all predicted images.

**Comment by valosekj** [comment]
Closing -- see summary: https://github.com/ivadomed/model-spinal-rootlets/issues/42
