### ISSUE TITLE
Ventral rootlets - results of third segmentation model

### ISSUE THREAD

**Issue by LouisThomasLapointe** [ivadomed/model-spinal-rootlets#40]
### **1) Dataset**
The training was done on 26 subjects from the spine-generic and OpenNeuro datasets. Manual segmentation of the ventral rootlets was done while the dorsal rootlets' segmentation were taken from the D5 dataset described [here](https://github.com/ivadomed/model-spinal-rootlets/tree/main/training). This dataset is named V3.

### **2) Model training**
nnUNet 3d_fullres model trained on 26 subjects.
To initialize the dataset, the following command was used:
`nnUNetv2_plan_and_preprocess -d 105 --verify_dataset_integrity -c  3d_fullres`

For starting the training, the following command was used:
`CUDA_VISIBLE_DEVICES=0 nnUNetv2_train 105 3d_fullres 0`

A fold all (no validation images) was also done on the dataset to improve the results (see section below).
`CUDA_VISIBLE_DEVICES=0 nnUNetv2_train 105 3d_fullres all`

For running the inference on new images, the following command was used:
`nnUNetv2_predict -i nnUNet_raw/Dataset105_M1/imagesTs -o nnUNet_results/Dataset105_M1/labels_results -d 105 -c 3d_fullres -f 0`
Where the Dataset105_M1/imagesTs folder contains the images on which inference was run.

### **3) Results**
<details><summary>Here are the learning curves for the training with fold 0 and fold all. </summary>

![training_log_2024_4_2_20_50_20](https://github.com/ivadomed/model-spinal-rootlets/assets/146556291/b7ee2fcc-52d9-4c65-bdb7-5014f8e5cd2b)

![training_log_2024_4_5_13_05_58](https://github.com/ivadomed/model-spinal-rootlets/assets/146556291/e54008e2-7542-495f-b204-02823a9304e6)
</details>

This next graph shows the performance of the V1 (Dataset101), V2 (Dataset104), V3_fold_0 and V3_fold_all (dataset105) models on the test subjects.
![image](https://github.com/ivadomed/model-spinal-rootlets/assets/146556291/ec7ef196-eb0d-4ab3-982e-7f3d20edeb37)

The V3_fold_0 algorithm performed really poorly on the test images. There were a lot of spinal level mislabelisation errors, often skipping the last spinal level (C8) completely. It also did some unexpected errors like segmenting two halves of an axial slice two different levels (see image below). Thus, I tried retraining the model on the same dataset, but with all the images as training material (fold_all). The V3_fold_all algorithm performed really well. It resolved any issue that the V3_fold_0 algorithm created and it greatly improved the overall results of the segmentation compared to the V1 and V2 model. The V3_fold_all is able to correctly assess the spinal level on all the test subjects, including the `sub-amu02_215.nii.gz` image that was really problematic for the V1 and V2 models. This improvement is reflected in the standard deviation on the mean Dice score, the V3_fold_all dataset scoring 0.0597 while the V1 and V2 models scored 0.1478 and 0.1028, respectively. The improvement is shown in the image below. 

### V3_fold_0 performance on `sub-amu02_215.nii.gz`
![image](https://github.com/ivadomed/model-spinal-rootlets/assets/146556291/855392b1-d62a-44f8-8b8e-b9e6416642f5)

### V3_fold_all performance on `sub-amu02_215.nii.gz`
![image](https://github.com/ivadomed/model-spinal-rootlets/assets/146556291/e6041fb1-7b9f-48dc-89ea-08727c91fafe)

Still, the overall Dice score obtained by the model can still be improved. The next step is to further expand the dataset. The V4 model is on the way with 31 training subjects.

**Comment by valosekj** [comment]
Closing -- see summary: https://github.com/ivadomed/model-spinal-rootlets/issues/42
