### ISSUE TITLE
Lumbar rootlets - images and labels have different resolution and dimensions

### ISSUE THREAD

**Issue by valosekj** [ivadomed/model-spinal-rootlets#46]
Raphaëlle Schlienger manually segmented T12 to S3 dorsal rootlets on 6 healthy participants on T2_ZOOMit images. 🎉 
During the procedure, she resampled the T2_ZOOMit images to 0.6x0.6x2mm resolution, as tracking rootlets at 0.3x0.3x0.5mm would have taken even longer:

> Generate empty rootlets image in 0.6x0.6x2mm resolution (do this directly in FSLeyes with the Resample Image option), 

This resampling caused not only the resolution to be different but also the dimensions. The borders of the label image containing rootlets exceed the T2_ZOOMit image (shown in orange; by setting `min` to `-1`):

<img width="800" alt="image" src="https://github.com/ivadomed/model-spinal-rootlets/assets/39456460/46930f98-a408-4351-b41f-47fd5a6fc8e1">

<details><summary>dim and pixdim2</summary>

```console
valosek@macbook-pro:~/data/experiments/lumbar_rootlets$ fin sub-CTS04_ses-SPpre_acq-zoomit_T2w.nii.gz
data_type	INT16
dim1		1024
dim2		372
dim3		192
dim4		1
datatype	4
pixdim1		0.292969
pixdim2		0.292969
pixdim3		0.500000
pixdim4		3.080000
cal_max		0.000000
cal_min		0.000000
file_type	NIFTI-1+                                                                                                                                                                                         /0.1s
valosek@macbook-pro:~/data/experiments/lumbar_rootlets$ fin sub-CTS04_ses-SPpre_T2w_rootlets_resampled.nii.gz
data_type	FLOAT32
dim1		85
dim2		417
dim3		125
dim4		1
datatype	16
pixdim1		0.600000
pixdim2		0.600000
pixdim3		2.000000
pixdim4		1.000000
cal_max		0.000000
cal_min		0.000000
file_type	NIFTI-1+
```

</details>

**Comment by valosekj** [comment]
Trying `sct_resample -ref`:

```console
sct_resample -i sub-CTS04_ses-SPpre_acq-zoomit_T2w.nii.gz -ref sub-CTS04_ses-SPpre_T2w_rootlets_resampled.nii.gz -x linear -o sub-CTS04_ses-SPpre_acq-zoomit_T2w_resampled.nii.gz
```

But, due to the different dimensions, the output looks:

<img width="800" alt="image" src="https://github.com/ivadomed/model-spinal-rootlets/assets/39456460/2ac819cd-8ed0-4e29-9937-50dbcb3b80bb">

**Comment by valosekj** [comment]
Trying `sct_resample -mm 0.6x0.6x2.0` followed by `sct_crop_image  -ref`

```console
# Resample T2_ZOOMit image to the rootlets resolution 
sct_resample -i sub-CTS04_ses-SPpre_acq-zoomit_T2w.nii.gz -mm 0.6x0.6x2.0 -x linear -o sub-CTS04_ses-SPpre_acq-zoomit_T2w_resampled2.nii.gz
# Crop the rootlets around the resampled T2_ZOOMit image
sct_crop_image -i sub-CTS04_ses-SPpre_T2w_rootlets_resampled.nii.gz -ref sub-CTS04_ses-SPpre_acq-zoomit_T2w_resampled2.nii.gz -o sub-CTS04_ses-SPpre_T2w_rootlets_resampled_crop.nii.gz
```

The rootlets label image (in orange) is rotated relative to the resampled T2_ZOOMit image:

<img width="800" alt="image" src="https://github.com/ivadomed/model-spinal-rootlets/assets/39456460/bc38540c-fd7b-4300-a6da-cb7f1265d91a">

**Comment by RaphaSchl** [comment]
Hi Jan,
It seems that using FLIRT with nearest neighbour interpolation to resample rootlets back into ZOOMit resolution works ! 
```
flirt -in sub-CTS04_ses-SPpre_T2w_rootlets_resampled.nii.gz -ref sub-CTS04_ses-SPpre_acq-zoomit_T2w.nii.gz -applyxfm -usesqform -out sub-CTS04_ses-SPpre_T2w_rootlets_resampled_inzoomit.nii.gz -interp nearestneighbour
```
The output orange rootlets are back in ZOOMit resolution : 
![rootlets_inzoomitres](https://github.com/ivadomed/model-spinal-rootlets/assets/62699870/79e12618-df94-4501-9a53-5edf6bde1439)

**Comment by valosekj** [comment]
Indeed! FLIRT works! Thank you! 🚀

**Comment by jcohenadad** [comment]
i'm curious as to why FLIRT worked, but not SCT. We should investigate (not a priority, but I don't want this to fall into a cracks) @joshuacwnewton

**Comment by RaphaSchl** [comment]
SCT works too :relaxed: I get exactly the same results as with the flirt command when I run :
 `sct_resample -i sub-CTS04_ses-SPpre_T2w_rootlets_resampled.nii.gz -ref sub-CTS04_ses-SPpre_acq-zoomit_T2w.nii.gz -x nn -o sub-CTS04_ses-SPpre_T2w_rootlets_resampled_inzoomitsct.nii.gz`
I think the issue might have been the type of interpolation used : nearest neighbor does the job !
